FROM node:19.7.0-alpine3.17

ENV NODE_ENV=production

WORKDIR /app

ADD package.json package-lock.json ./

RUN npm install --production
RUN npm install -g nodemon

ADD bin ./bin
ADD src ./src

CMD ["npm", "start"]
